name: Test Building Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 -t test-backpack-image .
