name: Publish Docker Container

on:
  release:
    types: [published]
  workflow_dispatch:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            easyselfhost/backpack:${{ github.ref }}
            ${{ github.event.release.prerelease == false && (github.event_name != 'workflow_dispatch' || inputs.publish_latest = 'true') && 'easyselfhost/backpack:latest' }}
